plugins:
  - jekyll-seo-tag

title: Free Email Dot Trick Generator (Gmail/Facebook/Twitter/Yahoo/Outlook and more..)

description: Generate emails from dot trick using fastest way possible that too free!

author: Navjot Singh Minhas

logo: /images/logo.png

twitter:
    username: NavjotSingh548
    card: http://navjotsinghminhas.com

social:
    name: Navjot Singh Minhas
    links:
        - http://navjotsinghminhas.com
        - https://www.linkedin.com/in/navjotsinghminhas

webmaster_verifications:
    google: temp